title: Street Light Consulting
tagline: Illuminating clarity in leadership and mission.
description: Helping leaders build clarity, systems, and faith-driven excellence.
url: https://streetlight.consulting
baseurl: ""

author: Rob S

collections:
  authors:
    output: true
    permalink: /consultants/:name/
  services:
    output: true
    permalink: /services/:name/



permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author

