title: Street Light Consulting
tagline: A team of faith-based consultants helping organizations grow through humility, clarity, and purpose.
description: Street Light Consulting helps leaders and mission-driven organizations build clarity, systems, and faith-driven excellence.
url: "https://streetlight.consulting"
baseurl: ""

author: Rob

# Collections
collections:
  authors:
    output: true
  services:
    output: true
    permalink: /services/:name/

# Permalinks for posts
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass/CSS options
sass:
  style: compressed

# Defaults for specific content types
defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Rob

